### ISSUE TITLE
Cannot initialize moveit planner

### ISSUE THREAD

**Issue by melgallad** [ravijo/baxter_moveit_tutorial#2]
Hello,

I followed the steps until initializing moveit planner. When I run this command: 
roslaunch baxter_moveit_tutorial moveit_init.launch

 I get the following error: 

RLException: [moveit_init.launch] is neither a launch file in package [baxter_moveit_tutorial] nor is [baxter_moveit_tutorial] a launch file name
The traceback for the exception was written to the log file

I have ros melodic

Any help would be appreciated. Thank you.

**Comment by ravijo** [comment]
@melgallad 

Sorry to hear that you faced this error.

I think you need to source your workspace. Please execute the following commands:

```
1. source /opt/ros/indigo/setup.bash
2. source /home/melgallad/catkin_ws/devel/setup.bash
```

Please note that, in the above commands, I am assuming you are using ROS indigo. Furthermore, you may need to modify the path in the 2nd command as per your environment. 

Finally, please verify inside the same terminal by executing the following command:

```
rospack -find baxter_moveit_tutorial
```

It should return the location to the package. 

Feel free to comment and open the issue if the problem persists.

Cheers!

**Comment by melgallad** [comment]
Hello again,

Thank you for your instructions. I tried them, but unfortunately I am facing the same issue.

I am using ROS melodic, could that be the problem?

I used rospack -find, but I am getting the following error:

Error: failed to parse command-line options: unrecognised option '%canonical_option%'

Just to be clear about what I did, I used git clone to clone the following 5 repositories into my workspace:

1) https://github.com/ros-planning/moveit_robots.git
2) https://github.com/RethinkRobotics/baxter
3) https://github.com/RethinkRobotics/baxter_interface
4) https://github.com/RethinkRobotics/baxter_tools
5) https://github.com/RethinkRobotics/baxter_examples

Am I missing anything?

Thank you very much again.

**Comment by ravijo** [comment]
@melgallad 

Thanks for the detailed information.

> I am using ROS melodic, could that be the problem?

I can not say anything because Baxter SDK was built for ROS Indigo a decade ago.

Moreover, this package is tested many times in ROS Indigo without any problem. 

Nevertheless, MoveIt supports ROS Melodic without any issues. You need to debug how and where Baxter SDK is breaking.

Cheers!
