### ISSUE TITLE
Error when executing a planned motion path

### ISSUE THREAD

**Issue by ans0ld2** [ravijo/baxter_moveit_tutorial#3]
Hi all 
When using the move module, I read the current state of the robot, then I set the coordinate offset in x, y, z, but I get an error from the robot:
![Снимок экрана 2022-11-03 в 09 08 17](https://user-images.githubusercontent.com/56612073/199999897-364813c7-7a6d-4007-ab2d-cdbb3f818263.png)
Tell me what could be the problem?

**Comment by ravijo** [comment]
@ans0ld2 

The error "Solution found but controller failed during execution" is coming from MoveIt. Please search MoveIt documentation or do a simple Google search.

Let me know your progress!

**Comment by ravijo** [comment]
Closing this issue as no further comments have been received. However, feel free to comment if the problem still exists.
